### PR TITLE
Generate fresh type-parameter name for modifyF

### LINKED ISSUE #299: Bad macro hygiene
Just got this from a coworker:

```
[error] Services.scala:11: type parameter F defined in method modifyF shadows type F defined in method errHandler. You may want to rename your type parameter, or possibly remove it.
[error] @Lenses case class Services[F[_]](
[error]  ^
[error] one error found
[error] (services/compile:compileIncremental) Compilation failed
```

We have a lot of scalac warnings enabled, and we force them to be errors. Changing `F[_]` to `G[_]` makes it work.

Macros should generate a fresh identifier for the type-parameter.

### PR DESCRIPTION
**Pull request by puffnfresh**
Fixes #299

### CODE REVIEW

**Comment by jedws** [comment]
:+1:

**Comment by NightRa** [comment]
It's failing to build on 2.10

**Comment by julien-truffaut** [comment]
I think you can use :
```scala
TypeName(c.freshName)
```

https://github.com/milessabin/macro-compat/blob/master/core/src/main/scala_2.10/macrocompat/macrocompat.scala#L157

**Comment by puffnfresh** [comment]
Think I fixed 2.10 but broke 2.11 :horse:

**Comment by puffnfresh** [comment]
@julien-truffaut trying that, thanks!

**Comment by puffnfresh** [comment]
There we go :fireworks:

**Comment by julien-truffaut** [comment]
:+1: Thanks, I didn't know about macro hygiene.
